// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX7QWw867QPxrGblIf9j-Rl7TCuu8PJSw',
    appId: '1:1083103099681:android:eabcc402d7cda2c4689c60',
    messagingSenderId: '1083103099681',
    projectId: 'wechat-98af6',
    storageBucket: 'wechat-98af6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKUuAMmg07tZ5JShjFI_6-v4NMvFoerQg',
    appId: '1:1083103099681:ios:8993e910f3a0bf00689c60',
    messagingSenderId: '1083103099681',
    projectId: 'wechat-98af6',
    storageBucket: 'wechat-98af6.appspot.com',
    androidClientId: '1083103099681-f45t9qcc6c6n7a3fi838flf4cjlcsdtf.apps.googleusercontent.com',
    iosClientId: '1083103099681-5nttmn1ld84j2tvb2a4fj1eeqhkhkjp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChatApp',
  );
}
